export { default as CardForm } from './CardForm'
export { default as SubtituloForm} from './SubtituloForm'
export { default as TabVentana } from './componentes/TabVentana'
export { default as VentanaLienzo } from './VentanaLienzo'
export { default as VentanaUsuario } from './VentanaUsuario'